Port 2222
ListenAddress 127.0.0.1
PasswordAuthentication no
KbdInteractiveAuthentication no
ChallengeResponseAuthentication no
PubkeyAuthentication yes
AuthenticationMethods publickey
PermitRootLogin no
AllowUsers marroyav
StrictModes yes
PrintMotd no
PrintLastLog no
X11Forwarding no
AllowTcpForwarding yes
AllowAgentForwarding no
GatewayPorts no
