Port 2222
ListenAddress 127.0.0.1
PasswordAuthentication no
KbdInteractiveAuthentication no
ChallengeResponseAuthentication no
PubkeyAuthentication yes
PermitRootLogin no
AllowUsers neutrino
PrintMotd no
PrintLastLog no
X11Forwarding no
AllowTcpForwarding yes
GatewayPorts no
